[package]
name = "miden-howto"
version = "0.1.0"
edition = "2024"

[dependencies]
miden-assembly = "0.15.0"
miden-lib = "0.10.1"
miden-processor = "0.15.0"
miden-stdlib = "0.15.0"
miden-vm = "0.15.0"
